"""Fix TypeDecorator import and confirm VIN

Revision ID: 3d45252e6987
Revises: c84c5446d07f
Create Date: 2025-07-19 10:00:30.218454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d45252e6987'
down_revision: Union[str, Sequence[str], None] = 'c84c5446d07f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('vin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'vin')
    # ### end Alembic commands ###
