"""Initial database setup

Revision ID: a008753ec6b8 # <--- YOUR ACTUAL NEW REVISION ID HERE
Revises:
Create Date: 2025-07-19 15:47:00.000000 # <--- YOUR ACTUAL CREATE DATE HERE

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Import postgresql dialect for JSONB


# revision identifiers, used by Alembic.
revision: str = 'a008753ec6b8' # <--- YOUR ACTUAL NEW REVISION ID HERE
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'leads',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('firstName', sa.String(), nullable=True),
        sa.Column('lastName', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('make', sa.String(), nullable=True),
        sa.Column('model', sa.String(), nullable=True),
        sa.Column('year', sa.String(), nullable=True),
        sa.Column('vin', sa.String(), nullable=True),
        sa.Column('bodyType', sa.String(), nullable=True),
        sa.Column('urgency', sa.String(), nullable=True),
        sa.Column('damageDescription', sa.Text(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('createdAt', sa.DateTime(), nullable=True),
        sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('glassToReplace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('addonServices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('preferredDate', sa.String(), nullable=True),
        sa.Column('preferredTime', sa.String(), nullable=True),
        sa.Column('preferredDaysTimes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_manual_entry', sa.Boolean(), nullable=True), # <--- Add this column
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=True)
    op.create_index(op.f('ix_leads_firstName'), 'leads', ['firstName'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_lastName'), 'leads', ['lastName'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=True) # <--- Corrected closing parenthesis
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_lastName'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_firstName'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
